apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-south-1
  version: "1.27"

managedNodeGroups:
  - name: ng-dedicated-1
    instanceType: t3a.micro
    desiredCapacity: 2
    volumeSize: 40
    volumeType: gp3
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-spot-1
    instanceType: t3a.medium
    desiredCapacity: 2
    spot: true
    labels:
      role: spot