apiVersion: v1
kind: Service
metadata:
    name: classifier-service
spec:
    selector:
        app.kubernetes.io/name: classifier
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: 7860
