apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: classifier-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classifier-deployment
  targetCPUUtilizationPercentage: 50
